import pandas as pd
import csv
from collections import defaultdict
import os
import random

# 1. Configuration des modèles de base (sans déclinaisons)
base_models = {
    "Graspifier": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 120.00,
        "price": 120.00,
        "weight": {"Homme": 81, "Femme": 65}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(40, 48)]},
        "Femme": {"sizes": [36,37,38,40,42]},
        "type": "Chaussures minimalistes",
        "category": "Fitness",
        "ground_type": "Salle",
        "stability": "Guidée",
        "drop": 0,
        "rating": {"Homme": 3.5, "Femme": 5},
        "1_star": {"Homme": 1, "Femme": 0},
        "2_star": {"Homme": 1, "Femme": 0},
        "3_star": {"Homme": 0, "Femme": 0},
        "4_star": {"Homme": 2, "Femme": 0},
        "5_star": {"Homme": 2, "Femme": 1},
        "review_count": {"Homme": 6, "Femme": 1},
        "is_recommended": {"Homme": 60, "Femme": 100},
        "colors": ["Noir", "Vert"],
        "news": {"Homme": True, "Femme": False},
        "sole_details": "",
        "upper": "",
        "material": "Caoutchouc Vibram EcoStep avec 30 % de contenu Vibram recyclé.",
        "utilisation": "Idéal pour l'entraînement en musculation et les routines en salle, où l'attention est portée sur l'équilibre et la sensation au sol.",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "La tige synthétique respirante et extensible de la Graspifier épouse véritablement le pied comme un gant, tandis que la semelle Max-Feel segmentée offre une excellente sensation au sol et une bonne articulation du pied, avec un équilibre optimal entre traction et durabilité.\nNotre caoutchouc Vibram EcoStep avec 30 % de contenu Vibram recyclé offre adhérence et traction, reconnaissant ainsi notre engagement envers la durabilité du produit.\nÉpaisseur totale de la semelle : 5 mm",
        "is_active": "true"
    },
    "KSO EVO": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 115.00,
        "price": 115.00,
        "weight": {"Homme": 139, "Femme": 99}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(40, 45)]},
        "Femme": {"sizes": [i for i in range(38, 42)]},
        "type": "chaussures minimalistes",
        "category": "Fitness",
        "ground_type": "Salle",
        "stability": "Modérée",
        "drop": 0,
        "rating": {"Homme": 4.3, "Femme": 4},
        "1_star": {"Homme": 29, "Femme": 22},
        "2_star": {"Homme": 20, "Femme": 12},
        "3_star": {"Homme": 32, "Femme": 11},
        "4_star": {"Homme": 39, "Femme": 21},
        "5_star": {"Homme": 285, "Femme": 102},
        "review_count": {"Homme": 405, "Femme": 168},
        "is_recommended": {"Homme": 85, "Femme": 79},
        "colors": ["Noir", "Blanc","Jaune","Orange"],
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle intérieure : 2 mm EVA + Doublure en Drilex\nSemelle extérieure : 3 mm de caoutchouc\nComposé : Vibram XS Trek",
        "upper": "Maille de Polyester\nFilm de protection et renforcement en polyuréthane\nLaçage rapide",
        "material": "Caoutchouc, dublure en Drilex, maille de polyester, film de protection en polyuréthane",
        "utilisation": "Fitness, pliométrie, mouvements primitifs, équilibre et renforcement.",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "Articulation et sensation au sol maximales. Adhérence assurée et protection essentielle.\nConception légère, aérée et simple de la tige réglable.\nCe modèle fait partie de notre gamme Medium Ground Feel. Philosophie du produit.",
        "is_active": "true"
    },
    "Breezandals": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 150.00,
        "price": 150.00,
        "weight": {"Homme": 182, "Femme": 134}, 
        "unisex": False,
        "Homme": {"sizes": [39,40,41,42,44]},
        "Femme": {"sizes": [36,38,39,40,41]},
        "type": "chaussures minimalistes",
        "category": "Trail",
        "ground_type": "Boue",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": {"Homme": 3.3, "Femme": 5},
        "1_star": {"Homme": 1, "Femme": 0},
        "2_star": {"Homme": 0, "Femme": 0},
        "3_star": {"Homme": 0, "Femme": 0},
        "4_star": {"Homme": 1, "Femme": 0},
        "5_star": {"Homme": 1, "Femme": 3},
        "review_count": {"Homme": 3, "Femme": 3},
        "is_recommended": {"Homme": 67, "Femme": 100},
        "colors": ["Noir", "Vert"],
        "news": {"Homme": False, "Femme": False},
        "sole_details": "",
        "upper": "",
        "material": "",
        "utilisation": "Idéal pour les sentiers, s’adapte également à l’eau.",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "La Breezandal est la chaussure d'extérieur la plus respirante de la collection Fivefingers.\nConçue pour être utilisée sur les sentiers, la semelle en caoutchouc MegaGrip excelle également sur les roches humides, ce qui fait de la Breezandal une chaussure idéale pour une utilisation près des rivières et des lacs.",
        "is_active": "true"
    },
    "Roadaround": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 180.00,
        "price": 180.00,
        "weight": {"Femme": 132},
        "unisex": False,
        "Femme": {"sizes": [i for i in range(37, 42)]},
        "type": "chaussures minimalistes",
        "category": "Casual",
        "ground_type": "Route",
        "stability": "Modérée",
        "drop": 0,
        "rating": {"Femme": 3.5},
        "1_star": {"Femme": 0},
        "2_star": {"Femme": 0},
        "3_star": {"Femme": 1},
        "4_star": {"Femme": 1},
        "5_star": {"Femme": 0},
        "review_count": {"Femme": 2},
        "is_recommended": {"Femme": 50},
        "colors": ["Noir", "Blanc"],
        "news": {"Femme": True},
        "sole_details": "",
        "upper": "",
        "material": "",
        "utilisation": "Convient parfaitement pour marcher sur des surfaces dures comme l'asphalte et le béton.",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "La tige en air-mesh super-respirante avec des panneaux réfléchissants rappelle les jours de gloire de la conception des baskets.\nLa semelle intermédiaire en EVA à double coussin d'air et la semelle extérieure articulée Vibram Carrarmato reflètent l'histoire de Vibram en termes d'image et de fonction. Notre caoutchouc Vibram EcoStep avec 30 % de contenu Vibram recyclé offre adhérence et traction, reconnaissant ainsi notre engagement en faveur de la durabilité des produits.\nÉpaisseur totale de la semelle : 11,5 mm",
        "is_active": "true"
    },
    "V-Aqua": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 130.00,
        "price": 130.00,
        "weight": {"Homme": 138, "Femme": 112}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(39, 46)]},
        "Femme": {"sizes": [i for i in range(36, 41)]},
        "type": "chaussures minimalistes",
        "category": "Trail",
        "ground_type": "Sentiers",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": {"Homme": 4.2, "Femme": 4},
        "1_star": {"Homme": 24, "Femme": 12},
        "2_star": {"Homme": 12, "Femme": 4},
        "3_star": {"Homme": 26, "Femme": 5},
        "4_star": {"Homme": 41, "Femme": 9},
        "5_star": {"Homme": 164, "Femme": 48},
        "review_count": {"Homme": 267, "Femme": 78},
        "is_recommended": {"Homme": 81, "Femme": 82},
        "colors": ["Noir", "Gris","Vert"],
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle Megagrip de 3,7 mm avec perforations drainantes pour une meilleure performance\nSemelle intérieure en EVA de 2 mm avec traitement silicone",
        "upper": "",
        "material": "",
        "utilisation": "Trekking dans les roches humides, Canoë, Kayak, Expéditions en rivière, Tubing, SUP.",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "Déplacez-vous naturellement dans et hors de l'eau tout ainsi que sur des terrains variés.\nLégère, fine et flexible sur le pied, la V-Aqua est idéale pour les situations où il n'est pas possible de marcher entièrement pieds nus.\nLa coupe ajustée et la conception légère, ainsi que les perforations de la Semelle Megagrip très résistante, permettent à l'eau de circuler rapidement dans la chaussure pour un séchage rapide.\nUn autre élément distinctif, l'impression en Silicone de pointe dans la doublure empêche tout glissement interne supplémentaire.",
        "is_active": "true"
    },
    "Scramkey": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 160.00,
        "price": 160.00,
        "weight": {"Homme": 406}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(39, 45)]},
        "type": "Chaussures minimalistes",
        "category": "Trail",
        "ground_type": "Sentiers",
        "stability": "Guidée",
        "drop": 0,
        "rating": {"Homme": 3.3},
        "1_star": {"Homme": 0},
        "2_star": {"Homme": 1},
        "3_star": {"Homme": 1},
        "4_star": {"Homme": 0},
        "5_star": {"Homme": 1},
        "review_count": {"Homme": 3},
        "is_recommended": {"Homme": 67},
        "colors": ["Noir", "Vert"],
        "news": {"Homme": True},
        "sole_details": "Crampon de traction VN098 + semelle-sangle de puissance intégrée, avec une zone 'adhérence élevée pré-tamponnée à l'avant pied.\nComposé : Megagrip 2.0\nCaoutchouc : 4mm",
        "upper": "Tige en polyester extensible avec superpositions en tpu aux principaux points d'abrasion ; col en néoprène extensible avec deux languettes de serrage. Contrefort de talon en tpu à haute abrasion.",
        "material": "",
        "utilisation": "Convient parfaitement à la pratique du scrambling sur des terrains accidentés et rocailleux.",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "La Scramkey est l'outil de mouvement naturel le plus puissant pour faire du scrambling en extérieur.\nAvec la technologie Traction lug, le power strap intégré à la semelle, la zone d'adhérence pré-tamponnée et le composé ultime Megagrip™ Elite, ce produit excelle dans les endroits rocailleux en extérieur.\nIl est doté d'une tige durable et sûre qui utilise une tige en polyester extensible avec des renforts TPU et une double fermeture auto-agrippante.", 
        "is_active": "true"
    },
    "V-Alpha": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 140.00,
        "price": 140.00,
        "weight": {"Homme": 136, "Femme": 103}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(42, 47)]},
        "Femme": {"sizes": [35,36,37,39,40]},
        "type": "chaussures minimalistes",
        "category": ["Trail","Running"],
        "ground_type": "Sentiers",
        "stability": "Neutre",
        "drop": 0,
        "rating": {"Homme": 4.3, "Femme": 4.4},
        "1_star": {"Homme": 22, "Femme": 13},
        "2_star": {"Homme": 24, "Femme": 12},
        "3_star": {"Homme": 33, "Femme": 29},
        "4_star": {"Homme": 65, "Femme": 36},
        "5_star": {"Homme": 285, "Femme": 190},
        "review_count": {"Homme": 429, "Femme": 280},
        "is_recommended": {"Homme": 88, "Femme": 85},
        "colors": {"Homme": ["Noir","Gris","Bleu","Orange","Marron"], "Femme": ["Noir","Vert"]},
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle extérieure en caoutchouc de 3,7 mm\nSemelle intérieure en Mousse de 2 mm pour un confort accru",
        "upper": "Empeigne en laine et matière synthétique pour une meilleure respirabilité et une réduction des odeurs",
        "material": "",
        "utilisation": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "La V-Alpha est un incontournable de l'entraînement en extérieur minimaliste, et est 100 % fidèle à notre philosophie d'origine : une protection du pied qui permet la perception sensorielle du sol, la performance et la dextérité. La semelle extérieure en caoutchouc flexible présente notre composé le plus polyvalent : Vibram Megagrip.\nCe composé assure à la fois l'adhérence et la durabilité dans le temps, sur un sol sec comme mouillé.",
        "is_active": "true"
    },
    "V-Soul": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 110.00,
        "price": 110.00,
        "weight": {"Femme": 91},
        "unisex": False,
        "Femme": {"sizes": [37,38,39,40,42]},
        "type": "chaussures minimalistes",
        "category": ["Fitness","Yoga"],
        "ground_type": "Salle",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": {"Femme": 4.4},
        "1_star": {"Femme": 23},
        "2_star": {"Femme": 14},
        "3_star": {"Femme": 27},
        "4_star": {"Femme": 66},
        "5_star": {"Femme": 261},
        "review_count": {"Femme": 391},
        "is_recommended": {"Femme": 89},
        "colors": ["Noir", "Blanc"],
        "news": {"Femme": True},
        "sole_details": "Semelle intérieure : Mousse en Polyuréthane de 2 mm + Doublure en Laine de Polyester\nCaoutchouc : composé XS Trek de 3 mm",
        "upper": "Polyester Brillant avec Réglage par Fermeture Auto-agrippante",
        "material": "",
        "utilisation": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "La V-Soul est notre dernière offre axée sur le fitness féminin et alternatif en intérieur.\nÉlégante et fine, elle peut être utilisée pour de nombreuses activités.\nLa V-Soul s'inscrit dans notre « philosophie de produit à sensation maximale », offrant un potentiel maximal d'articulation et de sensation au sol.\nDotée d'une coupe ajustable et sécurisée, elle est également très ouverte, légère et flexible.\nLes meilleures utilisations de cette chaussure sont le fitness fonctionnel, la plyométrie, le Pilates et le yoga, entre autres.",
        "is_active": "true"
    },
    "Furoshiki": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 100.00,
        "price": 100.00,
        "weight": {"Homme": 106, "Femme": 106}, 
        "unisex": False,
        "Homme": {"sizes": [40,41,43,44,45]},
        "Femme": {"sizes": [35,36,37,38,40]},
        "type": "chaussures minimalistes",
        "category": "Casual",
        "ground_type": "Route",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": {"Homme": 4.5, "Femme": 4.4},
        "1_star": {"Homme": 4, "Femme": 13},
        "2_star": {"Homme": 6, "Femme": 6},
        "3_star": {"Homme": 13, "Femme": 8},
        "4_star": {"Homme": 19, "Femme": 22},
        "5_star": {"Homme": 108, "Femme": 144},
        "review_count": {"Homme": 150, "Femme": 193},
        "is_recommended": {"Homme": 88, "Femme": 88},
        "colors": {"Homme": ["Noir","Bleu","Vert"], "Femme": ["Noir","Bleu","Vert","Rouge"]},
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle Vibram à faible densité pour une réduction du poids.",
        "upper": "Ajustement adaptable grâce à la forme anatomique et l’adhérence Vibram, offrant une empeigne extensible qui épouse parfaitement le pied.",
        "material": "Composition : 28 % Élasthane (Caoutchouc Extensible / Lycra), 72 % PA (Polyamide et Nylon)",
        "utilisation": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "Notre dernière et plus grande innovation en matière de chaussures alternatives encore améliorée !\nNous avons amélioré l'ajustement et la fonctionnalité, en adaptant le design de la semelle, la forme et l'ajustement de l’empeigne, ainsi que la partie orteils.\nEmportez-la partout… pour tout ce que vous faites et partout où vous allez, il y a Furoshiki !\nLe concept de ce type de chaussures est inspiré par la technique japonaise traditionnelle qui consiste à envelopper divers objets du quotidien dans un tissu pour les transporter.\nFuroshiki est la seule semelle du marché qui enveloppe l'ensemble du pied. Comme l’empeigne est fabriquée en tissu extensible, elle s'adaptera parfaitement à l'anatomie de chaque type de pied et le système de fermeture auto-agrippante permet un ajustement rapide et facile.\nGrâce à notre technologie révolutionnaire de semelles Vibram, Furoshiki offre le meilleur des conforts dans n'importe quel environnement !\nElle est également très facile à transporter et chaque paire est livrée avec son propre étui de voyage. L'ultime compagnon des chaussures de voyage, offrant protection, adhérence et confort.",
        "is_active": "true"
    },
       "One Quarter Toile": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 99.00,
        "price": 99.00,
        "weight": 88, 
        "unisex": True,
        "sizes": {"sizes": [i for i in range(39, 44)]},
        "type": "chaussures minimalistes",
        "category": "Casual",
        "ground_type": "Route",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": 3.5,
        "1_star": 0,
        "2_star": 0,
        "3_star": 1,
        "4_star": 1,
        "5_star": 0,
        "review_count": 2,
        "is_recommended": 50,
        "colors": ["Orange","Bleu","Rose"],
        "news": False,
        "sole_details": "Semelle Vibram à faible densité pour une réduction du poids.",
        "upper": "Ajustement adaptable grâce à la forme anatomique et l’adhérence Vibram, offrant une empeigne extensible qui épouse parfaitement le pied.",
        "material": "Composition : 28 % Élasthane (Caoutchouc Extensible / Lycra), 72 % PA (Polyamide et Nylon)",
        "utilisation": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "Notre dernière et plus grande innovation en matière de chaussures alternatives encore améliorée !\nNous avons amélioré l'ajustement et la fonctionnalité, en adaptant le design de la semelle, la forme et l'ajustement de l’empeigne, ainsi que la partie orteils.\nEmportez-la partout… pour tout ce que vous faites et partout où vous allez, il y a Furoshiki !\nLe concept de ce type de chaussures est inspiré par la technique japonaise traditionnelle qui consiste à envelopper divers objets du quotidien dans un tissu pour les transporter.\nFuroshiki est la seule semelle du marché qui enveloppe l'ensemble du pied. Comme l’empeigne est fabriquée en tissu extensible, elle s'adaptera parfaitement à l'anatomie de chaque type de pied et le système de fermeture auto-agrippante permet un ajustement rapide et facile.\nGrâce à notre technologie révolutionnaire de semelles Vibram, Furoshiki offre le meilleur des conforts dans n'importe quel environnement !\nElle est également très facile à transporter et chaque paire est livrée avec son propre étui de voyage. L'ultime compagnon des chaussures de voyage, offrant protection, adhérence et confort.",
        "is_active": "true"
    },
    "One Quarter Leather": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 105.00,
        "price": 105.00,
        "weight": {"Homme": 88}, 
        "unisex": False,
        "Homme": {"sizes": [41,42,44,45,46]},
        "type": "chaussures minimalistes",
        "category": "Casual",
        "ground_type": "Route",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": {"Homme": 4.4},
        "1_star": {"Homme": 12},
        "2_star": {"Homme": 4},
        "3_star": {"Homme": 11},
        "4_star": {"Homme": 25},
        "5_star": {"Homme": 121},
        "review_count": {"Homme": 173},
        "is_recommended": {"Homme": 89},
        "colors": {"Homme": "Noir"},
        "news": {"Homme": False},
        "sole_details": "Semelle dotée de la Technologie Vibram LITEBASE avec le composé Gumlite.\nDécouvrez la Technologie Vibram LITEBASE, qui réduit considérablement l'épaisseur et le poids des semelles extérieures en caoutchouc, tout en conservant l'adhérence et la traction attendues de Vibram. Cette nouvelle technologie réduit radicalement l'épaisseur de la semelle jusqu'à 50 % par rapport à une conception de semelle identique et permet de réduire le poids total jusqu'à 30 %.",
        "upper": "Ajustement adaptable grâce à la forme anatomique et l’adhérence Vibram, offrant une empeigne extensible qui épouse parfaitement le pied.",
        "material": "Semelle : Caoutchouc Gumlite Vibram et Technologie Vibram LITEBASE\nEmpeigne : Cuir",
        "utilisation": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "Relevant le défi de maintenir la performance pour ¼ du volume habituel, Vibram présente la nouvelle Vibram ¼ (Vibram One Quarter).\nAvec son design spécial en origami tridimensionnel et la technologie unique de sa semelle (Vibram LiteBase), Vibram ¼ est une chaussure légère, confortable et compacte, facile à transporter et parfaite pour les voyages.\nUn modèle au look moderne qui sera le compagnon idéal de votre temps libre, de vos aventures en ville et, pourquoi pas, un cadeau unique !",
        "is_active": "true"
    },
        "One Quarter Jeans": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 85.00,
        "price": 85.00,
        "weight": {"Homme": 110}, 
        "unisex": False,
        "Homme": {"sizes": [37,38,39,40,41,42]},
        "type": "chaussures minimalistes",
        "category": "Casual",
        "ground_type": "Route",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": {"Homme": 4.4},
        "1_star": {"Homme": 12},
        "2_star": {"Homme": 4},
        "3_star": {"Homme": 11},
        "4_star": {"Homme": 25},
        "5_star": {"Homme": 121},
        "review_count": {"Homme": 173},
        "is_recommended": {"Homme": 89},
        "colors": {"Homme": "Noir"},
        "news": {"Homme": False},
        "sole_details": "Semelle dotée de la Technologie Vibram LITEBASE avec le composé Gumlite.\nDécouvrez la Technologie Vibram LITEBASE, qui réduit considérablement l'épaisseur et le poids des semelles extérieures en caoutchouc, tout en conservant l'adhérence et la traction attendues de Vibram. Cette nouvelle technologie réduit radicalement l'épaisseur de la semelle jusqu'à 50 % par rapport à une conception de semelle identique et permet de réduire le poids total jusqu'à 30 %.",
        "upper": "Ajustement adaptable grâce à la forme anatomique et l’adhérence Vibram, offrant une empeigne extensible qui épouse parfaitement le pied.",
        "material": "Semelle : Caoutchouc Gumlite Vibram et Technologie Vibram LITEBASE\nEmpeigne : Jean",
        "utilisation": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "Relevant le défi de maintenir la performance pour ¼ du volume habituel, Vibram présente la nouvelle Vibram ¼ (Vibram One Quarter).\nAvec son design spécial en origami tridimensionnel et la technologie unique de sa semelle (Vibram LiteBase), Vibram ¼ est une chaussure légère, confortable et compacte, facile à transporter et parfaite pour les voyages.\nUn modèle au look moderne qui sera le compagnon idéal de votre temps libre, de vos aventures en ville et, pourquoi pas, un cadeau unique !",
        "is_active": "true"
    },
    "V-Run": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 160.00,
        "price": 160.00,
        "weight": {"Homme": 136, "Femme": 136}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(39, 43)]},
        "Femme": {"sizes": [i for i in range(35, 39)]},
        "type": "chaussures minimalistes",
        "category": "Running",
        "ground_type": ["Route","Sentiers"],
        "stability": "Neutre",
        "drop": 0,
        "rating": {"Homme": 4.2, "Femme": 4.1},
        "1_star": {"Homme": 19, "Femme": 17},
        "2_star": {"Homme": 17, "Femme": 15},
        "3_star": {"Homme": 21, "Femme": 20},
        "4_star": {"Homme": 26, "Femme": 20},
        "5_star": {"Homme": 169, "Femme": 119},
        "review_count": {"Homme": 252, "Femme": 191},
        "is_recommended": {"Homme": 85, "Femme": 82},
        "colors": {"Homme": ["Noir","Blanc"], "Femme": ["Noir","Rose"]},
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle intérieure : 2mm EVA + Doublure Drilex antimicrobien\nSemelle intermédiaire : 4mm EVA\nCaoutchouc : 2.5mm.",
        "upper": "Filet en Polyester Lycra Stretch + Microfibre en Polyester",
        "material": "",
        "utilisation": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "Ce modèle très confortable est doté d'une empeigne souple et ajourée pour maximiser la respirabilité.\nC'est une chaussure de course idéale pour faire la transition entre les chaussures traditionnelles et une approche plus minimaliste.\nLa construction de la semelle fine vous permet de sentir la Terre sous vos pieds.",
        "is_active": "true"
    },
}

def generate_random_stocks(sizes, mean=15, variation=10):
    """
    Génère des stocks aléatoires avec:
    - mean: stock moyen
    - variation: écart maximum par rapport à la moyenne
    """
    return [max(0, mean + random.randint(-variation, variation)) for _ in sizes]

# 2. Génération automatique des déclinaisons
def generate_gender_variants(model_name, model_data):
    variants = []
    
    if model_data["unisex"]:
        # Taille unique pour les deux genres
        
        for gender in ["Unisexe"]:
            variants.append({
                "model": model_name,
                "gender": gender,
                "full_name": f"{model_name}",
                "sizes": model_data["sizes"],
                "stocks": generate_random_stocks(model_data["sizes"]),
                **model_data
            })
    else:
        for gender in ["Homme", "Femme"]:
            if gender in model_data:
                variants.append({
                    "model": model_name,
                    "gender": gender,
                    "full_name": f"{model_name} {gender.capitalize()}",
                    "sizes": model_data[gender]["sizes"],
                    "stocks": generate_random_stocks(model_data[gender]["sizes"]),
                    **model_data
                })
    
    return variants

# 3. Génération des CSV
all_products = []
all_variants = []

for model_name, model_data in base_models.items():
    variants = generate_gender_variants(model_name, model_data)
    
    for variant in variants:
        all_products.append({
            "name": variant["full_name"],
            "sale": variant["sales"],
            "brand": variant["brand"],
            "base_price": variant["base_price"],
            "weight": variant["weight"].get(variant["gender"]) if isinstance(variant["weight"], dict) else variant["weight"],
            "type": variant["type"],
            "category": variant["category"],
            "gender": variant["gender"],
            "ground_type": variant["ground_type"],
            "stability": variant["stability"],
            "drop": variant["drop"],
            "rating": variant["rating"].get(variant["gender"]) if isinstance(variant["rating"], dict) else variant["rating"],
            "1_star": variant["1_star"].get(variant["gender"]) if isinstance(variant["1_star"], dict) else variant["1_star"],
            "2_star": variant["2_star"].get(variant["gender"]) if isinstance(variant["2_star"], dict) else variant["2_star"],
            "3_star": variant["3_star"].get(variant["gender"]) if isinstance(variant["3_star"], dict) else variant["3_star"],
            "4_star": variant["4_star"].get(variant["gender"]) if isinstance(variant["4_star"], dict) else variant["4_star"],
            "5_star": variant["5_star"].get(variant["gender"]) if isinstance(variant["5_star"], dict) else variant["5_star"],
            "review_count": variant["review_count"].get(variant["gender"]) if isinstance(variant["review_count"], dict) else variant["review_count"],
            "is_recommended": variant["is_recommended"].get(variant["gender"]) if isinstance(variant["is_recommended"], dict) else variant["is_recommended"],
            "news":  variant["news"].get(variant["gender"]) if isinstance(variant["news"], dict) else variant["news"],
            "sole_details": variant["sole_details"],
            "upper":variant["upper"],
            "material": variant["material"],
            "utilisation": variant["utilisation"],
            "care_instructions": variant["care_instructions"],
            "description": model_data.get("description", "")
        })
        
        # Fichier variants_config.csv
        if isinstance(variant["colors"], dict):
            colors_list = variant["colors"].get(variant["gender"])
        else:
            colors_list = variant["colors"]
        
        for color in colors_list:
            for i, size in enumerate(variant["sizes"]):
                all_variants.append({
                    "name": variant["full_name"],
                    "is_active" : variant["is_active"],
                    "colors": color,
                        "sku": variant["brand"][:6].upper()+"-"+(model_name.upper())+"-"+variant["gender"][:1].upper()+ "-" + str(size) + "-"+color.upper(),
                        "sizes": size,
                        "stocks": variant["stocks"][i]
            })
        

# 4. Export dans le répertoire courant
pd.DataFrame(all_products).to_csv(
    "products.csv",
    index=False,
    quoting=csv.QUOTE_ALL,
    escapechar="\\",
    encoding="utf-8"
)

pd.DataFrame(all_variants).to_csv(
    "variants_product.csv",
    index=False,
    quoting=csv.QUOTE_ALL,
    escapechar="\\",
    encoding="utf-8"
)