import pandas as pd
from collections import defaultdict
import os
import random
import csv

# 1. Configuration des modèles de base (sans déclinaisons)
base_models = {
        "Graspifier": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 120.00,
        "price": 120.00,
        "weight": {"Homme": 81, "Femme": 65}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(40, 48)]},
        "Femme": {"sizes": [36,37,38,40,42]},
        "type": "Chaussures minimalistes",
        "category": "Fitness",
        "ground_type": "Salle",
        "stability": "Guidée",
        "drop": 0,
        "rating": {"Homme": 3.5, "Femme": 5},
        "1_star": {"Homme": 1, "Femme": 0},
        "2_star": {"Homme": 1, "Femme": 0},
        "3_star": {"Homme": 0, "Femme": 0},
        "4_star": {"Homme": 2, "Femme": 0},
        "5_star": {"Homme": 2, "Femme": 1},
        "review_count": {"Homme": 6, "Femme": 1},
        "is_recommended": {"Homme": 60, "Femme": 100},
        "colors": ["Noir", "Vert"],
        "news": {"Homme": True, "Femme": False},
        "sole_details": "",
        "upper": "",
        "material": "Caoutchouc Vibram EcoStep avec 30 % de contenu Vibram recyclé.",
        "use_details": "Idéal pour l'entraînement en musculation et les routines en salle, où l'attention est portée sur l'équilibre et la sensation au sol.",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "La tige synthétique respirante et extensible de la Graspifier épouse véritablement le pied comme un gant, tandis que la semelle Max-Feel segmentée offre une excellente sensation au sol et une bonne articulation du pied, avec un équilibre optimal entre traction et durabilité.\nNotre caoutchouc Vibram EcoStep avec 30 % de contenu Vibram recyclé offre adhérence et traction, reconnaissant ainsi notre engagement envers la durabilité du produit.\nÉpaisseur totale de la semelle : 5 mm",
        "is_active": True,
        "use": "Occasionel"
    },
    "KSO EVO": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 115.00,
        "price": 115.00,
        "weight": {"Homme": 139, "Femme": 99}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(40, 45)]},
        "Femme": {"sizes": [i for i in range(38, 42)]},
        "type": "Chaussures minimalistes",
        "category": "Fitness",
        "ground_type": "Salle",
        "stability": "Modérée",
        "drop": 0,
        "rating": {"Homme": 4.3, "Femme": 4},
        "1_star": {"Homme": 29, "Femme": 22},
        "2_star": {"Homme": 20, "Femme": 12},
        "3_star": {"Homme": 32, "Femme": 11},
        "4_star": {"Homme": 39, "Femme": 21},
        "5_star": {"Homme": 285, "Femme": 102},
        "review_count": {"Homme": 405, "Femme": 168},
        "is_recommended": {"Homme": 85, "Femme": 79},
        "colors": ["Noir", "Blanc","Jaune","Orange"],
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle intérieure : 2 mm EVA + Doublure en Drilex\nSemelle extérieure : 3 mm de caoutchouc\nComposé : Vibram XS Trek",
        "upper": "Maille de Polyester\nFilm de protection et renforcement en polyuréthane\nLaçage rapide",
        "material": "Caoutchouc, dublure en Drilex, maille de polyester, film de protection en polyuréthane",
        "use_details": "Fitness, pliométrie, mouvements primitifs, équilibre et renforcement.",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "Articulation et sensation au sol maximales. Adhérence assurée et protection essentielle.\nConception légère, aérée et simple de la tige réglable.\nCe modèle fait partie de notre gamme Medium Ground Feel. Philosophie du produit.",
        "is_active": True,
        "use": "Occasionel"
    },
    "Breezandals": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 150.00,
        "price": 150.00,
        "weight": {"Homme": 182, "Femme": 134}, 
        "unisex": False,
        "Homme": {"sizes": [39,40,41,42,44]},
        "Femme": {"sizes": [36,38,39,40,41]},
        "type": "Chaussures minimalistes",
        "category": "Trail",
        "ground_type": "Boue",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": {"Homme": 3.3, "Femme": 5},
        "1_star": {"Homme": 1, "Femme": 0},
        "2_star": {"Homme": 0, "Femme": 0},
        "3_star": {"Homme": 0, "Femme": 0},
        "4_star": {"Homme": 1, "Femme": 0},
        "5_star": {"Homme": 1, "Femme": 3},
        "review_count": {"Homme": 3, "Femme": 3},
        "is_recommended": {"Homme": 67, "Femme": 100},
        "colors": ["Noir", "Vert"],
        "news": {"Homme": False, "Femme": False},
        "sole_details": "",
        "upper": "",
        "material": "",
        "use_details": "Idéal pour les sentiers, s’adapte également à l’eau.",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "La Breezandal est la chaussure d'extérieur la plus respirante de la collection Fivefingers.\nConçue pour être utilisée sur les sentiers, la semelle en caoutchouc MegaGrip excelle également sur les roches humides, ce qui fait de la Breezandal une chaussure idéale pour une use_details près des rivières et des lacs.",
        "is_active": True,
        "use": "Intensif"
    },
    "Roadaround": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 180.00,
        "price": 180.00,
        "weight": {"Femme": 132},
        "unisex": False,
        "Femme": {"sizes": [i for i in range(37, 42)]},
        "type": "Chaussures minimalistes",
        "category": "Casual",
        "ground_type": "Route",
        "stability": "Modérée",
        "drop": 0,
        "rating": {"Femme": 3.5},
        "1_star": {"Femme": 0},
        "2_star": {"Femme": 0},
        "3_star": {"Femme": 1},
        "4_star": {"Femme": 1},
        "5_star": {"Femme": 0},
        "review_count": {"Femme": 2},
        "is_recommended": {"Femme": 50},
        "colors": ["Noir", "Blanc"],
        "news": {"Femme": True},
        "sole_details": "",
        "upper": "",
        "material": "",
        "use_details": "Convient parfaitement pour marcher sur des surfaces dures comme l'asphalte et le béton.",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "La tige en air-mesh super-respirante avec des panneaux réfléchissants rappelle les jours de gloire de la conception des baskets.\nLa semelle intermédiaire en EVA à double coussin d'air et la semelle extérieure articulée Vibram Carrarmato reflètent l'histoire de Vibram en termes d'image et de fonction. Notre caoutchouc Vibram EcoStep avec 30 % de contenu Vibram recyclé offre adhérence et traction, reconnaissant ainsi notre engagement en faveur de la durabilité des produits.\nÉpaisseur totale de la semelle : 11,5 mm",
        "is_active": True,
        "use": "Intensif"
    },
    "V-Aqua": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 130.00,
        "price": 130.00,
        "weight": {"Homme": 138, "Femme": 112}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(39, 46)]},
        "Femme": {"sizes": [i for i in range(36, 41)]},
        "type": "Chaussures minimalistes",
        "category": "Trail",
        "ground_type": "Sentier",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": {"Homme": 4.2, "Femme": 4},
        "1_star": {"Homme": 24, "Femme": 12},
        "2_star": {"Homme": 12, "Femme": 4},
        "3_star": {"Homme": 26, "Femme": 5},
        "4_star": {"Homme": 41, "Femme": 9},
        "5_star": {"Homme": 164, "Femme": 48},
        "review_count": {"Homme": 267, "Femme": 78},
        "is_recommended": {"Homme": 81, "Femme": 82},
        "colors": ["Noir", "Gris","Vert"],
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle Megagrip de 3,7 mm avec perforations drainantes pour une meilleure performance\nSemelle intérieure en EVA de 2 mm avec traitement silicone",
        "upper": "",
        "material": "",
        "use_details": "Trekking dans les roches humides, Canoë, Kayak, Expéditions en rivière, Tubing, SUP.",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "Déplacez-vous naturellement dans et hors de l'eau tout ainsi que sur des terrains variés.\nLégère, fine et flexible sur le pied, la V-Aqua est idéale pour les situations où il n'est pas possible de marcher entièrement pieds nus.\nLa coupe ajustée et la conception légère, ainsi que les perforations de la Semelle Megagrip très résistante, permettent à l'eau de circuler rapidement dans la chaussure pour un séchage rapide.\nUn autre élément distinctif, l'impression en Silicone de pointe dans la doublure empêche tout glissement interne supplémentaire.",
        "is_active": True,
        "use": "Régulier"
    },
    "Scramkey": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 160.00,
        "price": 160.00,
        "weight": {"Homme": 406}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(39, 45)]},
        "type": "Chaussures minimalistes",
        "category": "Trail",
        "ground_type": "Sentier",
        "stability": "Guidée",
        "drop": 0,
        "rating": {"Homme": 3.3},
        "1_star": {"Homme": 0},
        "2_star": {"Homme": 1},
        "3_star": {"Homme": 1},
        "4_star": {"Homme": 0},
        "5_star": {"Homme": 1},
        "review_count": {"Homme": 3},
        "is_recommended": {"Homme": 67},
        "colors": ["Noir", "Vert"],
        "news": {"Homme": True},
        "sole_details": "Crampon de traction VN098 + semelle-sangle de puissance intégrée, avec une zone 'adhérence élevée pré-tamponnée à l'avant pied.\nComposé : Megagrip 2.0\nCaoutchouc : 4mm",
        "upper": "Tige en polyester extensible avec superpositions en tpu aux principaux points d'abrasion ; col en néoprène extensible avec deux languettes de serrage. Contrefort de talon en tpu à haute abrasion.",
        "material": "",
        "use_details": "Convient parfaitement à la pratique du scrambling sur des terrains accidentés et rocailleux.",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "La Scramkey est l'outil de mouvement naturel le plus puissant pour faire du scrambling en extérieur.\nAvec la technologie Traction lug, le power strap intégré à la semelle, la zone d'adhérence pré-tamponnée et le composé ultime Megagrip™ Elite, ce produit excelle dans les endroits rocailleux en extérieur.\nIl est doté d'une tige durable et sûre qui utilise une tige en polyester extensible avec des renforts TPU et une double fermeture auto-agrippante.", 
        "is_active": True,
        "use": "Régulier"
    },
    "V-Alpha": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 140.00,
        "price": 140.00,
        "weight": {"Homme": 136, "Femme": 103}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(42, 47)]},
        "Femme": {"sizes": [35,36,37,39,40]},
        "type": "Chaussures minimalistes",
        "category": ["Trail","Running"],
        "ground_type": "Sentier",
        "stability": "Neutre",
        "drop": 0,
        "rating": {"Homme": 4.3, "Femme": 4.4},
        "1_star": {"Homme": 22, "Femme": 13},
        "2_star": {"Homme": 24, "Femme": 12},
        "3_star": {"Homme": 33, "Femme": 29},
        "4_star": {"Homme": 65, "Femme": 36},
        "5_star": {"Homme": 285, "Femme": 190},
        "review_count": {"Homme": 429, "Femme": 280},
        "is_recommended": {"Homme": 88, "Femme": 85},
        "colors": {"Homme": ["Noir","Gris","Bleu","Orange","Marron"], "Femme": ["Noir","Vert"]},
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle extérieure en caoutchouc de 3,7 mm\nSemelle intérieure en Mousse de 2 mm pour un confort accru",
        "upper": "Empeigne en laine et matière synthétique pour une meilleure respirabilité et une réduction des odeurs",
        "material": "",
        "use_details": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "La V-Alpha est un incontournable de l'entraînement en extérieur minimaliste, et est 100 % fidèle à notre philosophie d'origine : une protection du pied qui permet la perception sensorielle du sol, la performance et la dextérité. La semelle extérieure en caoutchouc flexible présente notre composé le plus polyvalent : Vibram Megagrip.\nCe composé assure à la fois l'adhérence et la durabilité dans le temps, sur un sol sec comme mouillé.",
        "is_active": True,
        "use": "Intensif"
    },
    "V-Soul": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 110.00,
        "price": 110.00,
        "weight": {"Femme": 91},
        "unisex": False,
        "Femme": {"sizes": [37,38,39,40,42]},
        "type": "Chaussures minimalistes",
        "category": ["Fitness","Yoga"],
        "ground_type": "Salle",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": {"Femme": 4.4},
        "1_star": {"Femme": 23},
        "2_star": {"Femme": 14},
        "3_star": {"Femme": 27},
        "4_star": {"Femme": 66},
        "5_star": {"Femme": 261},
        "review_count": {"Femme": 391},
        "is_recommended": {"Femme": 89},
        "colors": ["Noir", "Blanc"],
        "news": {"Femme": True},
        "sole_details": "Semelle intérieure : Mousse en Polyuréthane de 2 mm + Doublure en Laine de Polyester\nCaoutchouc : composé XS Trek de 3 mm",
        "upper": "Polyester Brillant avec Réglage par Fermeture Auto-agrippante",
        "material": "",
        "use_details": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "La V-Soul est notre dernière offre axée sur le fitness féminin et alternatif en intérieur.\nÉlégante et fine, elle peut être utilisée pour de nombreuse activités.\nLa V-Soul s'inscrit dans notre « philosophie de produit à sensation maximale », offrant un potentiel maximal d'articulation et de sensation au sol.\nDotée d'une coupe ajustable et sécurisée, elle est également très ouverte, légère et flexible.\nLes meilleures use_detailss de cette chaussure sont le fitness fonctionnel, la plyométrie, le Pilates et le yoga, entre autres.",
        "is_active": True,
        "use": "Occasionel"
    },
    "Furoshiki": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 100.00,
        "price": 100.00,
        "weight": {"Homme": 106, "Femme": 106}, 
        "unisex": False,
        "Homme": {"sizes": [40,41,43,44,45]},
        "Femme": {"sizes": [35,36,37,38,40]},
        "type": "Chaussures minimalistes",
        "category": "Casual",
        "ground_type": "Route",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": {"Homme": 4.5, "Femme": 4.4},
        "1_star": {"Homme": 4, "Femme": 13},
        "2_star": {"Homme": 6, "Femme": 6},
        "3_star": {"Homme": 13, "Femme": 8},
        "4_star": {"Homme": 19, "Femme": 22},
        "5_star": {"Homme": 108, "Femme": 144},
        "review_count": {"Homme": 150, "Femme": 193},
        "is_recommended": {"Homme": 88, "Femme": 88},
        "colors": {"Homme": ["Noir","Bleu","Vert"], "Femme": ["Noir","Bleu","Vert","Rouge"]},
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle Vibram à faible densité pour une réduction du poids.",
        "upper": "Ajustement adaptable grâce à la forme anatomique et l’adhérence Vibram, offrant une empeigne extensible qui épouse parfaitement le pied.",
        "material": "Composition : 28 % Élasthane (Caoutchouc Extensible / Lycra), 72 % PA (Polyamide et Nylon)",
        "use_details": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "Notre dernière et plus grande innovation en matière de chaussures alternatives encore améliorée !\nNous avons amélioré l'ajustement et la fonctionnalité, en adaptant le design de la semelle, la forme et l'ajustement de l’empeigne, ainsi que la partie orteils.\nEmportez-la partout… pour tout ce que vous faites et partout où vous allez, il y a Furoshiki !\nLe concept de ce type de chaussures est inspiré par la technique japonaise traditionnelle qui consiste à envelopper divers objets du quotidien dans un tissu pour les transporter.\nFuroshiki est la seule semelle du marché qui enveloppe l'ensemble du pied. Comme l’empeigne est fabriquée en tissu extensible, elle s'adaptera parfaitement à l'anatomie de chaque type de pied et le système de fermeture auto-agrippante permet un ajustement rapide et facile.\nGrâce à notre technologie révolutionnaire de semelles Vibram, Furoshiki offre le meilleur des conforts dans n'importe quel environnement !\nElle est également très facile à transporter et chaque paire est livrée avec son propre étui de voyage. L'ultime compagnon des chaussures de voyage, offrant protection, adhérence et confort.",
        "is_active": True,
        "use": "Régulier"
    },
       "One Quarter Toile": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 99.00,
        "price": 99.00,
        "weight": 88, 
        "unisex": True,
        "sizes": {"sizes": [i for i in range(39, 44)]},
        "type": "Chaussures minimalistes",
        "category": "Casual",
        "ground_type": "Route",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": 3.5,
        "1_star": 0,
        "2_star": 0,
        "3_star": 1,
        "4_star": 1,
        "5_star": 0,
        "review_count": 2,
        "is_recommended": 50,
        "colors": ["Orange","Bleu","Rose"],
        "news": False,
        "sole_details": "Semelle Vibram à faible densité pour une réduction du poids.",
        "upper": "Ajustement adaptable grâce à la forme anatomique et l’adhérence Vibram, offrant une empeigne extensible qui épouse parfaitement le pied.",
        "material": "Composition : 28 % Élasthane (Caoutchouc Extensible / Lycra), 72 % PA (Polyamide et Nylon)",
        "use_details": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "Notre dernière et plus grande innovation en matière de chaussures alternatives encore améliorée !\nNous avons amélioré l'ajustement et la fonctionnalité, en adaptant le design de la semelle, la forme et l'ajustement de l’empeigne, ainsi que la partie orteils.\nEmportez-la partout… pour tout ce que vous faites et partout où vous allez, il y a Furoshiki !\nLe concept de ce type de chaussures est inspiré par la technique japonaise traditionnelle qui consiste à envelopper divers objets du quotidien dans un tissu pour les transporter.\nFuroshiki est la seule semelle du marché qui enveloppe l'ensemble du pied. Comme l’empeigne est fabriquée en tissu extensible, elle s'adaptera parfaitement à l'anatomie de chaque type de pied et le système de fermeture auto-agrippante permet un ajustement rapide et facile.\nGrâce à notre technologie révolutionnaire de semelles Vibram, Furoshiki offre le meilleur des conforts dans n'importe quel environnement !\nElle est également très facile à transporter et chaque paire est livrée avec son propre étui de voyage. L'ultime compagnon des chaussures de voyage, offrant protection, adhérence et confort.",
        "is_active": True,
        "use": "Intensif"
    },
    "One Quarter Leather": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 105.00,
        "price": 105.00,
        "weight": {"Homme": 88}, 
        "unisex": False,
        "Homme": {"sizes": [41,42,44,45,46]},
        "type": "Chaussures minimalistes",
        "category": "Casual",
        "ground_type": "Route",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": {"Homme": 4.4},
        "1_star": {"Homme": 12},
        "2_star": {"Homme": 4},
        "3_star": {"Homme": 11},
        "4_star": {"Homme": 25},
        "5_star": {"Homme": 121},
        "review_count": {"Homme": 173},
        "is_recommended": {"Homme": 89},
        "colors": {"Homme": "Noir"},
        "news": {"Homme": False},
        "sole_details": "Semelle dotée de la Technologie Vibram LITEBASE avec le composé Gumlite.\nDécouvrez la Technologie Vibram LITEBASE, qui réduit considérablement l'épaisseur et le poids des semelles extérieures en caoutchouc, tout en conservant l'adhérence et la traction attendues de Vibram. Cette nouvelle technologie réduit radicalement l'épaisseur de la semelle jusqu'à 50 % par rapport à une conception de semelle identique et permet de réduire le poids total jusqu'à 30 %.",
        "upper": "Ajustement adaptable grâce à la forme anatomique et l’adhérence Vibram, offrant une empeigne extensible qui épouse parfaitement le pied.",
        "material": "Semelle : Caoutchouc Gumlite Vibram et Technologie Vibram LITEBASE\nEmpeigne : Cuir",
        "use_details": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "Relevant le défi de maintenir la performance pour ¼ du volume habituel, Vibram présente la nouvelle Vibram ¼ (Vibram One Quarter).\nAvec son design spécial en origami tridimensionnel et la technologie unique de sa semelle (Vibram LiteBase), Vibram ¼ est une chaussure légère, confortable et compacte, facile à transporter et parfaite pour les voyages.\nUn modèle au look moderne qui sera le compagnon idéal de votre temps libre, de vos aventures en ville et, pourquoi pas, un cadeau unique !",
        "is_active": True,
        "use": "Intensif"
    },
        "One Quarter Jeans": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 85.00,
        "price": 85.00,
        "weight": {"Homme": 110}, 
        "unisex": False,
        "Homme": {"sizes": [37,38,39,40,41,42]},
        "type": "Chaussures minimalistes",
        "category": "Casual",
        "ground_type": "Route",
        "stability": "Minimaliste",
        "drop": 0,
        "rating": {"Homme": 4.4},
        "1_star": {"Homme": 12},
        "2_star": {"Homme": 4},
        "3_star": {"Homme": 11},
        "4_star": {"Homme": 25},
        "5_star": {"Homme": 121},
        "review_count": {"Homme": 173},
        "is_recommended": {"Homme": 89},
        "colors": {"Homme": "Noir"},
        "news": {"Homme": False},
        "sole_details": "Semelle dotée de la Technologie Vibram LITEBASE avec le composé Gumlite.\nDécouvrez la Technologie Vibram LITEBASE, qui réduit considérablement l'épaisseur et le poids des semelles extérieures en caoutchouc, tout en conservant l'adhérence et la traction attendues de Vibram. Cette nouvelle technologie réduit radicalement l'épaisseur de la semelle jusqu'à 50 % par rapport à une conception de semelle identique et permet de réduire le poids total jusqu'à 30 %.",
        "upper": "Ajustement adaptable grâce à la forme anatomique et l’adhérence Vibram, offrant une empeigne extensible qui épouse parfaitement le pied.",
        "material": "Semelle : Caoutchouc Gumlite Vibram et Technologie Vibram LITEBASE\nEmpeigne : Jean",
        "use_details": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "Relevant le défi de maintenir la performance pour ¼ du volume habituel, Vibram présente la nouvelle Vibram ¼ (Vibram One Quarter).\nAvec son design spécial en origami tridimensionnel et la technologie unique de sa semelle (Vibram LiteBase), Vibram ¼ est une chaussure légère, confortable et compacte, facile à transporter et parfaite pour les voyages.\nUn modèle au look moderne qui sera le compagnon idéal de votre temps libre, de vos aventures en ville et, pourquoi pas, un cadeau unique !",
        "is_active": True,
        "use": "Régulier"
    },
    "V-Run": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 160.00,
        "price": 160.00,
        "weight": {"Homme": 136, "Femme": 136}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(39, 43)]},
        "Femme": {"sizes": [i for i in range(35, 39)]},
        "type": "Chaussures minimalistes",
        "category": "Running",
        "ground_type": ["Route","Sentier"],
        "stability": "Neutre",
        "drop": 0,
        "rating": {"Homme": 4.2, "Femme": 4.1},
        "1_star": {"Homme": 19, "Femme": 17},
        "2_star": {"Homme": 17, "Femme": 15},
        "3_star": {"Homme": 21, "Femme": 20},
        "4_star": {"Homme": 26, "Femme": 20},
        "5_star": {"Homme": 169, "Femme": 119},
        "review_count": {"Homme": 252, "Femme": 191},
        "is_recommended": {"Homme": 85, "Femme": 82},
        "colors": {"Homme": ["Noir","Blanc"], "Femme": ["Noir","Rose"]},
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle intérieure : 2mm EVA + Doublure Drilex antimicrobien\nSemelle intermédiaire : 4mm EVA\nCaoutchouc : 2.5mm.",
        "upper": "Filet en Polyester Lycra Stretch + Microfibre en Polyester",
        "material": "",
        "use_details": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l’air libre",
        "description": "Ce modèle très confortable est doté d'une empeigne souple et ajourée pour maximiser la respirabilité.\nC'est une chaussure de course idéale pour faire la transition entre les chaussures traditionnelles et une approche plus minimaliste.\nLa construction de la semelle fine vous permet de sentir la Terre sous vos pieds.",
        "is_active": True,
        "use": "Régulier"
    },
    "KMD EVO": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 190.00,
        "price": 190.00,
        "weight": {"Homme": 210, "Femme": 160}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(40, 45)]},
        "Femme": {"sizes": [i for i in range(36, 41)]},
        "type": "Chaussures minimalistes",
        "category": "Running",
        "ground_type": ["Route", "Sentier"],
        "stability": "Modérée",
        "drop": 0,
        "rating": {"Homme" :4.4, "Femme": 4.4},
        "1_star": {"Homme" :2, "Femme": 2},
        "2_star": {"Homme": 4, "Femme": 1},
        "3_star": {"Homme": 0, "Femme": 1},
        "4_star": {"Homme": 8, "Femme": 1},
        "5_star": {"Homme": 32, "Femme": 20},
        "review_count": {"Homme": 43, "Femme": 25},
        "is_recommended": {"Homme": 85, "Femme": 83},
        "colors": {"Homme":["Noir","Vert","Blanc"], "Femme":["Noir","Marron"]},
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle intérieure : 2 mm EVA+Anti Microbial Drilex Sockliner\\n Semelle intermédiaire : 6 mm EVA",
        "upper": "100% Filament de polyester à faible élasticité",
        "material": "",
        "use_details": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "La KMD EVO est très appréciée des fans pour une bonne raison. Chaussure d'entraînement polyvalente pour l'intérieur et l'extérieur, elle est dotée d'une semelle intérieure Vibram Metaflex SL de 6 mm, d'une semelle extérieure Ecostep Recycle et d'une tige tricotée souple avec un système de laçage rapide.\\nLégère, souple et confortable, la KMD EVO convient parfaitement aux activités d'entraînement traditionnelles en intérieur et en extérieur, telles que les cours de fitness, l'haltérophilie, le cardio et d'autres exercices en salle de sport.\\nRemarque : Ce modèle Vibram FiveFingers utilise un composé de caoutchouc appelé Vibram EcoStep Recycle pour sa semelle. En raison de l'use_details de matériaux recyclés, le caoutchouc présente des taches blanches. Il ne s'agit pas d'une peinture, d'un défaut ou d'une salissure, mais simplement du résultat du caoutchouc utilisé.",
        "is_active": True,
        "use": "Occasionel"
    },
    "V-Trail 2.0": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 160.00,
        "price": 160.00,
        "weight": {"Homme": 182, "Femme": 142}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(41, 46)]},
        "Femme": {"sizes": [i for i in range(37, 42)]},
        "type": "Chaussures minimalistes",
        "category": "Trail",
        "ground_type": "Sentier",
        "stability": "Guidée",
        "drop": 0,
        "rating": {"Homme" :3.7, "Femme": 3.4},
        "1_star": {"Homme" : 45, "Femme": 19},
        "2_star": {"Homme": 28, "Femme": 18},
        "3_star": {"Homme": 24, "Femme": 23},
        "4_star": {"Homme": 49, "Femme": 19},
        "5_star": {"Homme": 129, "Femme": 43},
        "review_count": {"Homme": 275, "Femme": 122},
        "is_recommended": {"Homme": 72, "Femme": 61},
        "colors": "Noir",
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle Intérieure en EVA de 2 mm + Doublure en Polyester \\nSemelle Extérieure en Caoutchouc Megagrip de 3,7 mm",
        "upper": "",
        "material": "",
        "use_details": "Idéale pour courir dans la nature, sur les sentiers ou lors de courses d'obstacles : la chaussure de choix pour se déplacer sur des surfaces imprévisibles.",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "La V-Trail 2.0 offre les nouvelles et meilleures caractéristiques pour conquérir les sentiers avec aisance, y compris les deux couches de matière autour des orteils pour éviter les fissures des coutures et une empeigne améliorée plus hydrofuge que la version précédente. La V-Trail 2.0 est dotée d'une maille 3D Cocoon tissée dans la semelle extérieure pour la protéger des objets les plus tranchants pendant l'entraînement en extérieur, comme les pierres et les racines. La maille est tridimensionnelle, elle disperse le point d'impact sur toute la partie inférieure de la chaussure. Elle offre toujours une excellente sensation au sol et dextérité. Le composé de la semelle extérieure Megagrip offre une adhérence suprême sur terrain sec comme humide.",
        "is_active": True,
        "use": "Occasionel"
    },
    "V-Train 2.0": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 160.00,
        "price": 160.00,
        "weight": {"Homme": 220, "Femme": 175}, 
        "unisex": False,
        "Homme": {"sizes": [39,40,42,43,46]},
        "Femme": {"sizes": [35,36,38,40]},
        "type": "Chaussures minimalistes",
        "category": "Fitness",
        "ground_type": "Salle",
        "stability": "Guidée",
        "drop": 0,
        "rating": {"Homme" :4.4, "Femme": 4.3},
        "1_star": {"Homme" : 26, "Femme": 14},
        "2_star": {"Homme": 12, "Femme": 10},
        "3_star": {"Homme": 16, "Femme": 15},
        "4_star": {"Homme": 37, "Femme": 33},
        "5_star": {"Homme": 249, "Femme": 134},
        "review_count": {"Homme": 340, "Femme": 206},
        "is_recommended": {"Homme": 88, "Femme": 89},
        "colors": {"Homme": ["Noir", "Vert", "Gris"], "Femme": ["Noir", "Gris"]},
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle intérieure: Assise Plantaire en EVA de 2mm + Doublure en Polyester\\n Semelle intermédiaire: N/A\\n Caoutchouc: Semelle extérieure en caoutchouc XS Trek de 4mm",
        "upper": "Polyester, Panneaux Latéraux en TPU",
        "material": "",
        "use_details": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "La V-Train 2.0 est idéale pour les entraîneurs et athlètes expérimentés.\\n Bon niveau de sensation au sol et de protection avec une bonne articulation des orteils pour un bon équilibre et une stabilité optimale\\n Construction de l’empeigne spécialement conçue pour l'entraînement intensif, axée sur la durabilité et les performances\\n Cosses distinctives de traction de la corde dans la voûte\\n Nouveau système de laçage des panneaux avec fermeture auto-agrippante, sensation plus douce. Idéale pour les mouvements agressifs et latéraux\\n Composé caoutchouc XS Trek pour des performances polyvalentes en intérieur comme en extérieur",
        "is_active": True,
        "use": "Régulier"
    },
    "V-Trek": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 160.00,
        "price": 160.00,
        "weight": {"Homme": 185, "Femme": 139}, 
        "unisex": False,
        "Homme": {"sizes": [40,41,43,44,45]},
        "Femme": {"sizes": [36,37,39,40,42]},
        "type": "Chaussures minimalistes",
        "category": ["Trail", "Running"],
        "ground_type": ["Route", "Sentier"],
        "stability": "Modérée",
        "drop": 0,
        "rating": {"Homme" :4.3, "Femme": 4.3},
        "1_star": {"Homme" : 19, "Femme": 3},
        "2_star": {"Homme": 18, "Femme": 7},
        "3_star": {"Homme": 25, "Femme": 13},
        "4_star": {"Homme": 51, "Femme": 27},
        "5_star": {"Homme": 205, "Femme": 92},
        "review_count": {"Homme": 318, "Femme": 148},
        "is_recommended": {"Homme": 86, "Femme": 83},
        "colors": {"Homme": ["Noir", "Gris"], "Femme": ["Noir", "Violet"]},
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle Megagrip en caoutchouc de 4 mm pour des performances optimales sur diverses surfaces",
        "upper": "Empeigne extérieure en laine et matière synthétique pour plus d'extensibilité et de confort",
        "material": "",
        "use_details": "Trekking, Marche, Escalade, Sport urbain.",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "La V-Trek est idéale pour la marche, la randonnée et le trekking, et propose un style urbain très élégant. La semelle extérieure Flexible dotée de la technologie Megagrip est idéale pour une use_details en extérieur, pour une adhérence dans des conditions sèches comme humides. Une semelle intermédiaire en polyuréthane légèrement plus épaisse offre un confort supplémentaire, et notre matériau supérieur mélangé en laine et matière synthétique aide à améliorer la respirabilité et à réduire les odeurs. La coupe mi-haute et le système de laçage traditionnel permettent également un look sportif et décontracté. Les fibres synthétiques présentes dans la construction assurent la résistance mécanique et la durabilité.",
        "is_active": True,
        "use": "Intensif"
    },
    "V-Kumo": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 120.00,
        "price": 120.00,
        "weight": {"Femme": 112}, 
        "unisex": False,
        "Femme": {"sizes": [i for i in range(38,42)]},
        "type": "Chaussures minimalistes",
        "category": "Casual",
        "ground_type": "Route",
        "stability": "Guidée",
        "drop": 0,
        "rating": {"Femme": 3},
        "1_star": {"Femme": 3},
        "2_star": {"Femme": 0},
        "3_star": {"Femme": 2},
        "4_star": {"Femme": 0},
        "5_star": {"Femme": 3},
        "review_count": {"Femme": 8},
        "is_recommended": {"Femme": 60},
        "colors": {"Femme": ["Noir", "Vert"]},
        "news": {"Femme": False},
        "sole_details": "Semelle intérieure : 2 mm EVA + Doublure en Drilex\\n Semelle extérieure : 3 mm de caoutchouc\\n Composé : Vibram XS Trek",
        "upper": "Polyester matelassé",
        "material": "",
        "use_details": "Trekking, Marche, Escalade, Sport urbain.",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "Cette chaussure décontractée de tous les jours est élégante, confortable et offre une sensation maximale au sol. La tige en polyester matelassé est agréable au pied et s'attache bien grâce à une double bande auto-agrippante. La semelle extérieure est en caoutchouc Vibram XS Trek, qui offre une bonne adhérence pour les activités quotidiennes telles que promener le chien, faire les courses ou passer du temps en plein air avec des amis.",
        "is_active": True,
        "use": "Occasionel"
    },
    "Spyridon EVO": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 135.00,
        "price": 135.00,
        "weight": {"Homme": 141, "Femme": 141}, 
        "unisex": False,
        "Homme": {"sizes": [i for i in range(42, 47)]},
        "Femme": {"sizes": [35,37,38,40]},
        "type": "Chaussures minimalistes",
        "category": ["Trail", "Running"],
        "ground_type": ["Route", "Sentier"],
        "stability": "Modérée",
        "drop": 0,
        "rating": {"Homme" :3.5, "Femme": 3.9},
        "1_star": {"Homme" : 3, "Femme": 0},
        "2_star": {"Homme": 4, "Femme": 2},
        "3_star": {"Homme": 4, "Femme": 2},
        "4_star": {"Homme": 1, "Femme": 6},
        "5_star": {"Homme": 10, "Femme": 5},
        "review_count": {"Homme": 22, "Femme": 15},
        "is_recommended": {"Homme": 59, "Femme": 73},
        "colors": {"Homme": ["Noir"], "Femme": ["Noir"]},
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle intérieure : 3 mm Polyuréthane + Doublure en Drilex Antimicrobien\\n Semelle extérieure : 3,5 mm de caoutchouc\\n Composé : Vibram Megagrip",
        "upper": "Polyester",
        "material": "",
        "use_details": "Idéale pour courir dans la nature, sur les sentiers ou lors de courses d'obstacles : la chaussure de choix pour se déplacer sur des surfaces imprévisibles.",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "Une évolution naturelle de notre chaussure de trail populaire durable, légère et respirante, et dispose désormais d'un système de fermeture sécurisé à sangle auto-agrippante pour une meilleure stabilité. La semelle de cette chaussure de trail robuste est conçue avec la technologie Vibram 3D Cocoon, une fine couche protectrice en maille croisée qui offre une protection légère sur les sentiers et les terrains irréguliers. L'ajout de Vibram Megagrip offre une adhérence supérieure sur les surfaces humides comme sèches. La Spyridon EVO est née pour l'extérieur, idéale pour le trail, les randonnées, les courses d'obstacles et tout ce que Mère Nature peut mettre à vos pieds.",
        "is_active": True,
        "use": "Intensif"
    },
    "V-Lynx": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 150.00,
        "price": 150.00,
        "weight": {"Homme": 420, "Femme": 320}, 
        "unisex": False,
        "Homme": {"sizes": [39,41,42,44,47]},
        "Femme": {"sizes": [35,38,39,40]},
        "type": "Chaussures minimalistes",
        "category": "Casual",
        "ground_type": ["Route", "Sentier"],
        "stability": "Minimaliste",
        "drop": 0,
        "rating": {"Homme" :3.6, "Femme": 3.8},
        "1_star": {"Homme" : 2, "Femme": 0},
        "2_star": {"Homme": 1, "Femme": 1},
        "3_star": {"Homme": 0, "Femme": 0},
        "4_star": {"Homme": 6, "Femme": 3},
        "5_star": {"Homme": 3, "Femme": 1},
        "review_count": {"Homme": 12, "Femme": 5},
        "is_recommended": {"Homme": 58, "Femme": 80},
        "colors": {"Homme": ["Noir", "Gris"], "Femme": ["Noir", "Gris"]},
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle intérieure : Polyuréthane souple 4 mm ;\\n Semelle extérieure : 4 mm ;\\n Composant de la semelle : Vibram XS Trek",
        "upper": "Matière supérieure hydrofuge et rembourrée, fermeture à glissière thermo-soudée",
        "material": "",
        "use_details": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "Ce modèle est équipé d'une semelle intérieure en polyuréthane souple de 4 mm et d'une semelle extérieure flexible en caoutchouc Vibram de 4 mm, dotée du composé de caoutchouc XS TREK pour une traction et une adhérence sur des terrains variés. La tige déperlante et rembourrée garde vos pieds au chaud les jours de bruine, tandis que la fermeture éclair thermo-soudée améliore l'isolation. Parfaite pour le quotidien de l'automne et de l'hiver.",
        "is_active": True,
        "use": "Intensif"
    },
    "EL-X Knit": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 125.00,
        "price": 125.00,
        "weight": {"Homme": 140, "Femme": 110}, 
        "unisex": False,
        "Homme": {"sizes": [40,42,43,45,46]},
        "Femme": {"sizes": [37,39,40,42]},
        "type": "Chaussures minimalistes",
        "category": ["Fitness","Yoga"],
        "ground_type": ["Salle"],
        "stability": "Modérée",
        "drop": 0,
        "rating": {"Homme" :4.4, "Femme": 4.6},
        "1_star": {"Homme" : 1, "Femme": 1},
        "2_star": {"Homme": 3, "Femme": 1},
        "3_star": {"Homme": 1, "Femme": 2},
        "4_star": {"Homme": 4, "Femme": 3},
        "5_star": {"Homme": 24, "Femme": 27},
        "review_count": {"Homme": 33, "Femme": 34},
        "is_recommended": {"Homme": 91, "Femme": 91},
        "colors": {"Homme": ["Noir", "Gris"], "Femme": ["Noir", "Gris"]},
        "news": {"Homme": False, "Femme": False},
        "sole_details": "Semelle intérieure : 2 mm EVA\\n Semelle intermédiaire : N/A\\n Caoutchouc : 3 MM",
        "upper": "Tissée",
        "material": "",
        "use_details": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "Cette version améliorée d'un style populaire allie le confort d'enfilage d'une empeigne tissée souple à une semelle extérieure minimaliste et adhérente. La semelle XS Trek de 3 mm offre un équilibre optimal entre traction et durabilité sur des terrains variés. La EL-X Knit offre une bonne sensation au sol pour ceux qui recherchent une expérience minimaliste, et est idéale pour une use_details au quotidien dans un style décontracté.",
        "is_active": True,
        "use": "Intensif"
    },
    "KOS Vintage": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 110.00,
        "price": 110.00,
        "weight": {"Homme": 175}, 
        "unisex": False,
        "Homme": {"sizes": [41,43,44,45,47]},
        "type": "Chaussures minimalistes",
        "category": "Casual",
        "ground_type": "Route",
        "stability": "Guidée",
        "drop": 0,
        "rating": {"Homme": 4.4},
        "1_star": {"Homme": 2},
        "2_star": {"Homme": 1},
        "3_star": {"Homme": 1},
        "4_star": {"Homme": 9},
        "5_star": {"Homme": 21},
        "review_count": {"Homme": 34},
        "is_recommended": {"Homme": 84},
        "colors": {"Homme": ["Vert", "Blanc"]},
        "news": {"Homme": False},
        "sole_details": "Semelle intérieure : Microfibre en Polyester\\n Semelle intermédiaire : N/A\\n Caoutchouc : 1,5 mm",
        "upper": "Polyamide Extensible, Polyester, Polyuréthane",
        "material": "",
        "use_details": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "Une nouvelle version d'un classique intemporel, l'édition limitée de la KSO Vintage célèbre le meilleur de ce que les chaussures minimalistes FiveFingers ont à offrir. Le polyamide extensible, fin et résistant et la maille extensible respirante enveloppent votre pied, pour un ajustement confortable qui ne laisse rien entrer. L’empeigne est respirante et à sèche rapidement, pour permettre une use_details dans l'eau ou par temps humide, tandis que le système populaire de fermeture auto-agrippante assure un ajustement sûr. De plus, la semelle extérieure en caoutchouc performant XS Trek, non marquante, est extrêmement polyvalente et offre une excellente adhérence sur les surfaces sèches comme humides. La KSO Vintage est idéale aussi bien pour une use_details quotidienne décontractée que pour des entraînements en salle de sport, et même pour les aventures sur les sentiers. Elle est conçue pour les vrais minimalistes qui veulent se connecter pleinement avec la Terre.",
        "is_active": True,
        "use": "Régulier"
    },
    "KMD sport": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 120.00,
        "price": 120.00,
        "weight": 180, 
        "unisex": True,
        "sizes": [i for i in range(38,44)],
        "type": "Chaussures minimalistes",
        "category": ["Fitness", "Running"],
        "ground_type": "Salle",
        "stability": "Modérée",
        "drop": 0,
        "rating": 4.6,
        "1_star": 0,
        "2_star": 3,
        "3_star": 4,
        "4_star": 6,
        "5_star": 56,
        "review_count": 70,
        "is_recommended": 96,
        "colors": ["Jaune"],
        "news": False,
        "sole_details": "Semelle extérieure en caoutchouc de 4 mm\\n Assise plantaire en polyuréthane de 2 mm",
        "upper": "",
        "material": "",
        "use_details": "",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "Pensée pour l'athlète d'aujourd'hui, Vibram FiveFingers gagne en intensité avec la Vibram FiveFingers KMD Sport. Cette conception multisports conserve tout ce que nous aimons de la KSO avec des améliorations fonctionnelles qui plaisent aux amateurs de fitness les plus actifs. Pour la toute première fois, Vibram présente une semelle de 2 mm sans couture pour réduire les frottements. Les fermetures auto-agrippantes au talon et sur le cou-de-pied permettent de fixer l’empeigne en nylon extensible aux contours de votre pied, comme une seconde peau. La KMD Sport ne serait pas complète sans une semelle extérieure en caoutchouc Vibram TC1 de 4 mm qui offre l'adhérence et la protection dont vous avez besoin pour une large variété d'activités. Lavage en Machine / Séchage à l'Air Libre.",
        "is_active": True,
        "use": "Régulier"
    },
        "V-street": {
        "brand": "Vibram fivefingers",
        "sales": 0,
        "base_price": 215.00,
        "price": 215.00,
        "weight": 230, 
        "unisex": True,
        "sizes": [39,41,42,44,45],
        "type": "Chaussures minimalistes",
        "category": "Casual",
        "ground_type": "Route",
        "stability": "Guidée",
        "drop": 0,
        "rating": 3.5,
        "1_star": 1,
        "2_star": 2,
        "3_star": 4,
        "4_star": 0,
        "5_star": 5,
        "review_count": 12,
        "is_recommended": 67,
        "colors": ["Noir","Gris","Blanc"],
        "news": False,
        "sole_details": "12mm Total Thickness of sole.​\\n MIDSOLE: 6mm Foam\\n RUBBER: 4mm Rubber",
        "upper": "Stretch poly-wool blend with knit-sleeve collar; speed lace system closure.",
        "material": "",
        "use_details": "Idéal pour la marche urbaine sur des surfaces dures et artificielles.",
        "care_instructions": "Lavage en machine à froid / Séchage à l'air libre",
        "description": "Une édition limitée de la collaboration Brandblack® Vibram Fivefingers combine une semelle Vibram Fivefingers confortable avec du caoutchouc Vibram XS Trek. Cette semelle propulse et amortit, ce qui en fait le choix idéal pour les promenades urbaines. La conception lisse de la tige associe les meilleurs matériaux : une tige en laine mélangée pour une saisonnalité maximale, et un col de chaussette extensible pour un confort ajusté.",
        "is_active": True,
        "use": "Intensif"
    }
}

def generate_random_stocks(sizes, mean=15, variation=10):
    """
    Génère des stocks aléatoires avec:
    - mean: stock moyen
    - variation: écart maximum par rapport à la moyenne
    """
    return [max(0, mean + random.randint(-variation, variation)) for _ in sizes]

# 2. Génération automatique des déclinaisons
def generate_gender_variants(model_name, model_data):
    variants = []

    if model_data["unisex"]:
        # Taille unique pour les deux genres
        
        for gender in ["Unisexe"]:
            variants.append({
                "model": model_name,
                "gender": gender,
                "full_name": f"{model_name}",
                "sizes": model_data["sizes"],
                "stocks": generate_random_stocks(model_data["sizes"]),
                **model_data
            })
    else:
        for gender in ["Homme", "Femme"]:
            if gender in model_data:
                variants.append({
                    "model": model_name,
                    "gender": gender,
                    "full_name": f"{model_name} {gender.capitalize()}",
                    "sizes": model_data[gender]["sizes"],
                    "stocks": generate_random_stocks(model_data[gender]["sizes"]),
                    **model_data
                })
    
    return variants

# 3. Génération des CSV
all_products = []
all_variants = []
all_categories = []
all_ground_types = []

for model_name, model_data in base_models.items():
    variants = generate_gender_variants(model_name, model_data)
    
    for variant in variants:
        all_products.append({
            "sale": variant["sales"],
            "name": variant["full_name"],
            "brand": variant["brand"],
            "base_price": variant["base_price"],
            "weight": variant["weight"].get(variant["gender"]) if isinstance(variant["weight"], dict) else variant["weight"],
            "type": variant["type"],
            "category": variant["category"],
            "gender": variant["gender"],
            "ground_type": variant["ground_type"],
            "stability": variant["stability"],
            "drop": variant["drop"],
            "use": variant["use"],
            "rating": variant["rating"].get(variant["gender"]) if isinstance(variant["rating"], dict) else variant["rating"],
            "1_star": variant["1_star"].get(variant["gender"]) if isinstance(variant["1_star"], dict) else variant["1_star"],
            "2_star": variant["2_star"].get(variant["gender"]) if isinstance(variant["2_star"], dict) else variant["2_star"],
            "3_star": variant["3_star"].get(variant["gender"]) if isinstance(variant["3_star"], dict) else variant["3_star"],
            "4_star": variant["4_star"].get(variant["gender"]) if isinstance(variant["4_star"], dict) else variant["4_star"],
            "5_star": variant["5_star"].get(variant["gender"]) if isinstance(variant["5_star"], dict) else variant["5_star"],
            "review_count": variant["review_count"].get(variant["gender"]) if isinstance(variant["review_count"], dict) else variant["review_count"],
            "is_recommended": variant["is_recommended"].get(variant["gender"]) if isinstance(variant["is_recommended"], dict) else variant["is_recommended"],
            "news":  variant["news"].get(variant["gender"]) if isinstance(variant["news"], dict) else variant["news"],
            "sole_details": variant["sole_details"],
            "upper":variant["upper"],
            "material": variant["material"],
            "use_details": variant["use_details"],
            "care_instructions": variant["care_instructions"],
            "description": model_data.get("description", "")
        })
        
        # Fichier variants_config.csv
        if isinstance(variant["colors"], dict):
            colors_list = variant["colors"].get(variant["gender"])
        else:
            colors_list = variant["colors"]
        
        for color in colors_list:
            for i, size in enumerate(variant["sizes"]):
                all_variants.append({
                    "name": variant["full_name"],
                    "sku": variant["brand"][:6].upper()+"-"+(model_name.upper())+"-"+variant["gender"][:1].upper()+ "-" + str(size) + "-"+color.upper(),
                    "stocks": variant["stocks"][i],
                    "is_active" : variant["is_active"],
                    "price":variant["price"],
                    "colors": color,
                    "sizes": size,
            })
        
        categories_list = variant["category"]

        if isinstance(categories_list, str):
            categories_list = [categories_list]
        for category in categories_list:
            all_categories.append({
                "name":  variant["full_name"],
                "category": category,
            })

        ground_types_list = variant["ground_type"]

        if isinstance(ground_types_list, str):
            ground_types_list = [ground_types_list]
        for ground_type in ground_types_list:
            all_ground_types.append({
                "name":  variant["full_name"],
                "ground_type": ground_type,
            })

# 4. Export dans le dossier seed_data à la racine de backend
script_dir = os.path.dirname(os.path.abspath(__file__))
backend_dir = os.path.dirname(script_dir)
seed_data_dir = os.path.join(backend_dir, "seed_data")
os.makedirs(seed_data_dir, exist_ok=True)
products_path = os.path.join(seed_data_dir, "products.csv")
variants_path = os.path.join(seed_data_dir, "product_variants.csv")
categories_path = os.path.join(seed_data_dir, "product_categories.csv")
ground_types_path = os.path.join(seed_data_dir, "product_ground_types.csv")

pd.DataFrame(all_products).to_csv(
    products_path,
    index=False,
    quoting=csv.QUOTE_ALL,
    escapechar="\\",
    encoding="utf-8"
)

pd.DataFrame(all_variants).to_csv(
    variants_path,
    index=False,
    quoting=csv.QUOTE_ALL,
    escapechar="\\",
    encoding="utf-8"
)

pd.DataFrame(all_categories).to_csv(
    categories_path,
    index=False,
    quoting=csv.QUOTE_ALL,
    escapechar="\\",
    encoding="utf-8"
)

pd.DataFrame(all_ground_types).to_csv(
    ground_types_path,
    index=False,
    quoting=csv.QUOTE_ALL,
    escapechar="\\",
    encoding="utf-8"
)