export type Product = {
  id: number;
  name: string;
  brand: string;
  price: number;
  size: number[];
  type?: string;
  activity?: string;
  gender?: string;
  description?: string;
  image_url?: string;
  image_url_full?: string;
  images?: string[];
  stock?: number;
  rating?: number;
  review_count?: number;
  color?: string;
  colors?: string[];
  stability?: string;
  drop?: number;
  ground_types?: string[];
};
